// TODO in this file, fire all commands needed to deploy the application : creation of database + tables, creation of minio bucket...
// TODO implement caching with redis, server caching and client caching
// TODO deployment ? Electron ? WHere to store data ? minio ? docker ? where to store doc ? swagger/compodoc...
// TODO tests, UT, FT, E2E, Black Box, load testing...
// TODO documentation (directory structure readme for server and client, flow of creation of card (with file IDs), flow of pagination in client with emitters)
// TODO implement redirects after operations (delete, update, create... refire last GET request)


